---
- name: Create a file on localhost
  hosts: localhost
  tasks:
    - name: Ensure the file is present
      file:
        path: /tmp/file.txt
        state: touch

    - name: Write content to the file
      copy:
        dest: /home/gova/file.txt
        content: "This is the content of the file."
